const PDFDocument = require('pdfkit');

/**
 * Generate a professional PDF prescription and write to stream
 * @param {Object} prescription - Prescription Mongoose object with populated doctor, patient, user details
 * @param {Object} res - Express Response object to stream the PDF
 */
const generatePrescriptionPDF = (prescription, res) => {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  // Stream directly to the express response
  doc.pipe(res);

  // Colors
  const primaryColor = '#005f73';
  const secondaryColor = '#0a9396';
  const darkColor = '#2b2d42';
  const lightColor = '#f4f6f9';

  // --- HEADER SECTION ---
  // Draw primary accent header block
  doc.rect(0, 0, 595.28, 80).fill(primaryColor);
  
  // Hospital Title
  doc.fillColor('#ffffff')
     .font('Helvetica-Bold')
     .fontSize(22)
     .text('LIFELINE GENERAL HOSPITAL', 50, 28, { align: 'left' });

  doc.fontSize(10)
     .font('Helvetica')
     .text('123 Health Ave, Medical District | Ph: +1 555-0199 | care@lifeline.com', 50, 55, { align: 'left' });

  // RX Symbol
  doc.fillColor('#ffffff')
     .font('Helvetica-Bold')
     .fontSize(36)
     .text('Rx', 500, 22, { align: 'right' });

  doc.moveDown(4);

  // --- METADATA SECTION (DOCTOR & PATIENT) ---
  doc.fillColor(darkColor);
  
  // Doctor Info
  doc.font('Helvetica-Bold').fontSize(14).text('DOCTOR INFORMATION', 50, 110);
  doc.rect(50, 128, 230, 2).fill(secondaryColor);
  
  doc.fillColor(darkColor).font('Helvetica-Bold').fontSize(11).text(`Dr. ${prescription.doctor.user.name}`, 50, 140);
  doc.font('Helvetica').fontSize(10)
     .text(`Department: ${prescription.doctor.department.name}`, 50, 155)
     .text(`Specialization: ${prescription.doctor.specialization}`, 50, 170)
     .text(`Email: ${prescription.doctor.user.email}`, 50, 185);

  // Patient Info
  doc.font('Helvetica-Bold').fontSize(14).text('PATIENT INFORMATION', 315, 110);
  doc.rect(315, 128, 230, 2).fill(secondaryColor);
  
  doc.fillColor(darkColor).font('Helvetica-Bold').fontSize(11).text(prescription.patient.user.name, 315, 140);
  doc.font('Helvetica').fontSize(10)
     .text(`Age: ${prescription.patient.age} years | Gender: ${prescription.patient.gender || 'N/A'}`, 315, 155)
     .text(`Blood Group: ${prescription.patient.bloodGroup}`, 315, 170)
     .text(`Date: ${new Date(prescription.date).toLocaleDateString()}`, 315, 185);

  doc.moveDown(7);

  // --- PRESCRIPTION LIST SECTION ---
  doc.font('Helvetica-Bold').fontSize(14).text('MEDICATIONS PRESCRIBED', 50, 230);
  doc.rect(50, 248, 495, 2).fill(primaryColor);
  
  let currentY = 265;

  // Table Headers
  doc.font('Helvetica-Bold').fontSize(10).fillColor(primaryColor);
  doc.text('Medication Name', 55, currentY);
  doc.text('Dosage', 220, currentY);
  doc.text('Frequency', 330, currentY);
  doc.text('Duration', 450, currentY);

  currentY += 15;
  doc.moveTo(50, currentY).lineTo(545, currentY).stroke('#cccccc');
  currentY += 10;

  // Table Rows
  doc.font('Helvetica').fontSize(10).fillColor(darkColor);
  prescription.medications.forEach((med) => {
    // Check if we need a new page
    if (currentY > 700) {
      doc.addPage();
      currentY = 50;
    }

    doc.text(med.name, 55, currentY);
    doc.text(med.dosage, 220, currentY);
    doc.text(med.frequency, 330, currentY);
    doc.text(med.duration, 450, currentY);

    currentY += 20;
    doc.moveTo(50, currentY).lineTo(545, currentY).stroke('#eeeeee');
    currentY += 10;
  });

  // --- INSTRUCTIONS ---
  if (prescription.instructions) {
    if (currentY > 650) {
      doc.addPage();
      currentY = 50;
    }
    
    currentY += 10;
    doc.font('Helvetica-Bold').fontSize(12).fillColor(primaryColor).text('ADDITIONAL INSTRUCTIONS', 50, currentY);
    currentY += 18;
    doc.font('Helvetica').fontSize(10).fillColor(darkColor).text(prescription.instructions, 55, currentY, { width: 485, align: 'justify' });
  }

  // --- FOOTER & SIGNATURE ---
  // Position signature near bottom
  const footerY = 730;
  doc.moveTo(350, footerY).lineTo(520, footerY).stroke(primaryColor);
  doc.font('Helvetica-Bold').fontSize(10).fillColor(darkColor).text(`Dr. ${prescription.doctor.user.name}`, 350, footerY + 5, { align: 'center', width: 170 });
  doc.font('Helvetica').fontSize(8).fillColor('#777777').text('Authorized Signature', 350, footerY + 18, { align: 'center', width: 170 });

  // Bottom footer note
  doc.rect(0, 800, 595.28, 42).fill(primaryColor);
  doc.fillColor('#ffffff')
     .font('Helvetica')
     .fontSize(8)
     .text('This prescription is digitally signed and generated by the Lifeline HMS. Please consult your physician in case of emergencies.', 0, 812, { align: 'center', width: 595.28 });

  doc.end();
};

module.exports = { generatePrescriptionPDF };
